local C = require("orca.colors")

return {
	texComment = {link = "@comment"},
	texCommentTodo = {link = "@text.todo"},
	texDelim = {link = "@punctuation.bracket"},
	texCmd = {link = "@function"},
	texOpt = {fg = C.blue.bright},
	texOptSep = {link = "@punctuation.delimiter"},
	texOptEqual = {link = "texOptSep"},
	texArg = {link = "texOpt"},
	texSpecialChar = {fg = C.orange.base},
	texCmdInput = {fg = C.purple.base},
	texCmdBib = {link = "texCmdInput"},
	texCmdClass = {link = "texOpt"},
	texCmdPackage = {fg = C.cyan.base},
	texFileOpt = {fg = C.green.base},
	texFileArg = {link = "texOpt"},
	texFilesOpt = {link = 'texFileOpt'},
	texFilesArg = {link = "texFileArg"},
	texCmdTitle = {link = "texCmd"},
	texTitleArg = {link = "texOpt"},
	texCmdAuthor = {link = "texCmd"},
	texAuthorOpt = {link = "texOpt"},
	texCmdPart = {fg = C.blue.base},
	texPartArgTitle = {fg = C.green.base, bold = true},
	texCmdEnv = {fg = C.blue.base},
	texEnvArgName = {fg = C.blue.bright},
	texCmdRef = {fg = C.cyan.base},
	texRefArg = {fg = C.fg},
	texMathZone = {fg = C.fg},
	texMathDelimZone = {fg = C.red.base},
	texMathDelim = {fg = C.purple.base},
	texMathDelimMod = {fg = C.purple.base},
	texMathOper = {link = "@operator"},
	texMathSuperSub = {link = "@operator"},
	texMathEnvArgName = {link = "texEnvArgName"},
	texLength = {fg = C.orange.base},
	texLigature = {fg = C.white_grey.comment_grey},
	texCmdAccent = {fg = C.yellow.base},
	texCmdDef = {fg = C.red.base},
	texDefArgName = {fg = C.fg},
	texDefParm = {fg = C.fg},
	texCmdItem = {fg = C.blue.base},
	texStyleBold = {fg = C.orange.base, bold = true},
	texStyleItal = {fg = C.cyan.base, italic = true},
	texStyleUnder = {underline = true},
	texStyleBoth = {bold = true, italic = true},
	texStyleBoldUnder = {underline = true, bold = true},
	texStyleItalUnder = {italic = true, underline = true},
	texStyleBoldItalUnder = {italic = true, bold = true, underline = true},
	texTabularChar = {fg = C.red.base}
}
